name: CI/CD Lint and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check TypeScript
      run: npm run check || true
    
    - name: Build application
      run: npm run build || true
    
    - name: Run health check
      run: |
        echo "Health check would run here if tests were configured"
        echo "Add test scripts to package.json to enable testing"
    
    - name: Check for security vulnerabilities
      run: npm audit --audit-level=high || true